# Generated by Django 5.0 on 2023-12-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockModel",
            fields=[
                ("entry_id", models.AutoField(primary_key=True, serialize=False)),
                ("index_name", models.CharField(max_length=40)),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shares_traded", models.BigIntegerField()),
                ("turnover", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
